
#spring cloud
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.94:10700/eureka/
  instance:
    ip-address: 192.168.1.22
    prefer-ip-address: true
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

spring:
  cdkj:
    redis:
      port: 6379
      database: 1
      host[0]: 192.168.1.95
      password:
      namespaces: lesmarthome-pms